name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: fastrapier/swe-proj/.github/workflows/go-lint.yml@main
    # with:
    #   go-version: "1.26"
    #   working-directory: "."

  test:
    uses: fastrapier/swe-proj/.github/workflows/go-test.yml@main
    # with:
    #   go-version: "1.26"
    #   working-directory: "."

  build:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: fastrapier/swe-proj/.github/workflows/docker-build-push.yml@main
    with:
      image-name: playback-service
    permissions:
      contents: read
      packages: write
